name: run

on:
  schedule:
    - cron: '0 * * * *'  # Spouští se každou hodinu
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run all scrapers and generate pozemky.json
        run: python run_all_scrapers.py

      - name: Upload pozemky.json to FTP
        run: |
          curl -T pozemky.json ftp://${{ secrets.FTP_HOST }}/ \
            --user ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}
