name: Spustit scraper

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Nastavit Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalace závislostí
        run: pip install -r requirements.txt

      - name: Spuštění scraperu
        run: python scraper.py

      - name: Nahrání na FTP přes curl
        run: |
          curl -T pozemky.json ftp://${{ secrets.FTP_HOST }}/public_html/www/pozemekdomice/
          --user ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASS }}

